# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13a11c2935b57f3455491624029eb9ceb6be4e8294aa11cc33b9c956798c7b38ecbb5024efbcb181a1184d12f956fc30280dc53fd37c0220d78950428611a743

test:
  secret_key_base: 51c2d22d58b8af1e5bd744f875c1b815738bc9ee60440fe9485140ec7289132c7a31a6d3328f5fe94427cdaf25344c6af7cca8ed969cbf7716a5c75d44384f34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
